[build]
  command = "npm run build"
  publish = "dist"

[functions]
  directory = "netlify/functions"

[[redirects]]
  from = "/api/orders"
  to = "/.netlify/functions/create-order"
  status = 200

[[redirects]]
  from = "/api/admin-orders"
  to = "/.netlify/functions/admin-orders"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
