create table if not exists public.orders (
  id bigint generated by default as identity primary key,
  order_number text not null unique,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  display_date text not null,
  customer_name text not null,
  contact text not null,
  address text not null,
  notes text,
  order_total numeric(12, 2) not null default 0,
  item_count integer not null default 0,
  status text not null default 'pending',
  email_sent boolean not null default false,
  email_reason text,
  packing_slip_filename text,
  invoice_filename text,
  items jsonb not null default '[]'::jsonb,
  packing_slip_pdf_base64 text,
  invoice_spreadsheet_base64 text,
  constraint orders_status_check check (
    status in (
      'pending',
      'confirmed',
      'packing',
      'shipped',
      'completed',
      'cancelled'
    )
  )
);

create index if not exists orders_created_at_idx
  on public.orders (created_at desc);

create index if not exists orders_status_idx
  on public.orders (status);

create index if not exists orders_customer_name_idx
  on public.orders (customer_name);

alter table public.orders enable row level security;

drop policy if exists "Service role can manage orders" on public.orders;

create policy "Service role can manage orders"
  on public.orders
  for all
  using (auth.role() = 'service_role')
  with check (auth.role() = 'service_role');
